SERVER_SOURCE_DIR=./src/server
SERVER_BINARY_DIR=./bin
SERVER_BINARY_NAME=gopresent
SERVER_BINARY_PATH=$(SERVER_BINARY_DIR)/$(SERVER_BINARY_NAME)

CLIENT_SOURCE_DIR=./src/client
FILE=main.go
CLIENT_BINARY_DIR=./public
CLIENT_BINARY_NAME=main.wasm
CLIENT_BINARY_PATH=$(CLIENT_BINARY_DIR)/$(CLIENT_BINARY_NAME)

all: client server
server:
	go build -o $(SERVER_BINARY_PATH) $(SERVER_SOURCE_DIR)
client: 
	GOOS=js GOARCH=wasm go build -o $(CLIENT_BINARY_PATH) $(CLIENT_SOURCE_DIR)/$(FILE)
clean: 
	git rm $(SERVER_BINARY_PATH) $(CLIENT_BINARY_PATH)
run: all
	$(SERVER_BINARY_PATH)
deps:
	go get ./...
